# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetzUnite' do

  use_frameworks!

  pod 'RNCryptor', '~> 5.0'
  pod 'Alamofire', '~> 4.3'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'PromiseKit', '~> 4.0'
  pod 'IQActionSheetPickerView'
  pod 'ZCAnimatedLabel'
  pod 'ImageSlideshow'
  pod 'KSToastView', '0.5.7'
  pod 'WormTabStrip', '~> 1.0'
 
end

# Workaround for Cocoapods issue #7606
	post_install do |installer|
    		installer.pods_project.build_configurations.each do |config|
        	config.build_settings.delete('CODE_SIGNING_ALLOWED')
        	config.build_settings.delete('CODE_SIGNING_REQUIRED')
    	end
end
